volumes:
  venv:

services:
    moriyama_task:
        build:
            context: .
            dockerfile: Dockerfile
        image: OPPU_reproduce
        volumes:
          - type: bind
            source: .
            target: /app
          - venv:/app/.venv
          - venv:/app/.cache
        environment:
          NVIDIA_VISIBLE_DEVICES: all
          NVIDIA_DRIVER_CAPABILITIES: all
        deploy:
          resources:
            reservations:
              devices:
                - capabilities:
                    - gpu
        command: tail -f /dev/null
        container_name: OPPU_reproduce

